  
version: '3'

services:
 app:
   image: kwood475/sharefi:1.0.0
   build:
     context: .
   ports:
     - "8041:8041"
   volumes:
     - ./app:/app
   command: >
     sh -c "python manage.py wait_for_db &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8041"