# Generated by Django 2.1.7 on 2020-04-27 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=70)),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
