# Generated by Django 2.1.7 on 2020-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=70)),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
