# Generated by Django 2.1.7 on 2020-04-26 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
