# Generated by Django 2.1.7 on 2020-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0002_stockinfo_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='price',
            field=models.FloatField(),
        ),
    ]
